### ISSUE TITLE
import com.kii.sample.chat.R;

### ISSUE THREAD

**Issue by lionstone** [KiiPlatform/KiiChat#1]
Hi! This project looks great - I'm unable to build in eclipse with the error 

The import com.kii.sample.chat.R cannot be 
 resolved

Could you provide more specific instructions on how to get set up in Eclipse? 

I've linked the android-support-v4.jar library - and tried cleaning the project but to no avail so far.

Thanks! Look forward to trying out Kii :)

**Comment by thestardeepu** [comment]
need help app show message   (unfortunatetly, kiichat has stopped)
